version: '3.8'

services:
  openfga-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENFGA_API_URL=${OPENFGA_API_URL:-}
      - OPENFGA_STORE_ID=${OPENFGA_STORE_ID:-}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    volumes:
      # For development, mount the source code
      - ./src:/app/src:ro