site_name: OpenFGA MCP
site_description: Model Context Protocol (MCP) server for OpenFGA
site_url: https://github.com/evansims/openfga-mcp
repo_url: https://github.com/evansims/openfga-mcp
repo_name: evansims/openfga-mcp

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Usage: usage.md
  - Reference:
      - API Reference: api-reference.md
  - Development:
      - Release Process: release-process.md
      - Contributing: ../CONTRIBUTING.md
  - Changelog: ../CHANGELOG.md
