name: Release

# This workflow handles the entire release process for the project:
# 1. Runs quality checks (tests, linting, type checking)
# 2. Bumps version based on conventional commits
# 3. Generates changelog
# 4. Creates GitHub release
# 5. Publishes to PyPI
# 6. Sends notification

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version increment type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
      prerelease:
        description: "Is this a prerelease?"
        required: true
        default: false
        type: boolean
      python_version:
        description: "Python version to use"
        required: false
        default: ""
        type: string

# Set default permissions to minimum required
permissions:
  contents: read

jobs:
  # Load configuration using the reusable workflow
  config:
    name: Load Configuration
    uses: ./.github/workflows/load-config.yml
    with:
      python_version_override: ${{ github.event.inputs.python_version }}

  # Run tests, linting, and type checking by reusing existing workflows
  test:
    name: Run Tests
    needs: config
    uses: ./.github/workflows/test.yml
    with:
      python-versions: '["${{ needs.config.outputs.python_version }}"]'
      coverage: true
      security-check: true

  lint:
    name: Run Linting
    needs: config
    uses: ./.github/workflows/lint.yml
    with:
      python-version: ${{ needs.config.outputs.python_version }}

  type-check:
    name: Run Type Checking
    needs: config
    uses: ./.github/workflows/type-check.yml
    with:
      python-version: ${{ needs.config.outputs.python_version }}

  # Bump version, update changelog, and create tag
  prepare-release:
    name: Prepare Release
    needs: [config, test, lint, type-check]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      tag: ${{ steps.get_version.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Use the composite action for Python setup
      - name: Set up Python
        uses: ./.github/actions/python-setup
        with:
          python-version: ${{ needs.config.outputs.python_version }}
          dependencies: "commitizen"
          cache: "true"

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      # Use Makefile to bump version
      - name: Bump version
        id: bump_version
        run: |
          echo "Bumping version using ${{ github.event.inputs.version_type }} increment..."
          # Modify the Makefile target to accept version type as an argument
          if ! RELEASE_TYPE=${{ github.event.inputs.version_type }} make release-ci; then
            echo "::error::Failed to bump version. Check if there are any conventional commits that warrant a version bump."
            exit 1
          fi
          echo "Version bumped successfully!"

      - name: Get version
        id: get_version
        run: |
          VERSION=$(python -c "from configparser import ConfigParser; c = ConfigParser(); c.read('pyproject.toml'); print(c['project']['version'].strip('\"'))")
          TAG="v$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Detected version: $VERSION (tag: $TAG)"

      - name: Generate changelog
        run: |
          echo "Generating changelog for version ${{ steps.get_version.outputs.version }}..."
          cz changelog --incremental > CHANGELOG.md
          echo "Changelog generated successfully!"
          echo "Preview of changelog:"
          cat CHANGELOG.md | head -n 10

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.tag }}
          name: Release ${{ steps.get_version.outputs.tag }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}

  # Build and publish to PyPI
  publish:
    name: Build and Publish
    needs: [config, prepare-release]
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.prepare-release.outputs.tag }}

      # Use the composite action for Python setup
      - name: Set up Python
        uses: ./.github/actions/python-setup
        with:
          python-version: ${{ needs.config.outputs.python_version }}
          cache: "true"

      - name: Verify version
        run: |
          PACKAGE_VERSION=$(python -c "from configparser import ConfigParser; c = ConfigParser(); c.read('pyproject.toml'); print(c['project']['version'].strip('\"'))")
          if [ "$PACKAGE_VERSION" != "${{ needs.prepare-release.outputs.version }}" ]; then
            echo "::error::Version mismatch! Expected version ${{ needs.prepare-release.outputs.version }} but found $PACKAGE_VERSION"
            exit 1
          fi
          echo "Version verification successful: $PACKAGE_VERSION"

      # Use Makefile to build the package
      - name: Build package
        run: make build
        env:
          UV_CACHE_DIR: ${{ runner.temp }}/uv-cache

      # Generate Software Bill of Materials (SBOM)
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          output-file: sbom.spdx.json
          artifact-name: sbom.spdx.json

      # Upload SBOM as an artifact
      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json
          retention-days: 90

      # Use Makefile to publish the package
      - name: Verify and publish package
        run: |
          echo "Verifying package before publishing..."
          # List the built distributions
          ls -la dist/

          # Publish to PyPI using Makefile
          echo "Publishing package to PyPI..."
          make publish
        env:
          UV_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          retention-days: 7

  # Notify about the release
  notify:
    name: Notify
    needs: [config, prepare-release, publish]
    if: always()
    uses: ./.github/workflows/notify.yml
    with:
      message: "Release ${{ needs.prepare-release.outputs.version }} process completed"
      details: |
        Version: ${{ needs.prepare-release.outputs.version }}
        Tag: ${{ needs.prepare-release.outputs.tag }}
        GitHub Release: https://github.com/${{ github.repository }}/releases/tag/${{ needs.prepare-release.outputs.tag }}
        PyPI Package: https://pypi.org/project/${{ needs.config.outputs.package_name }}/${{ needs.prepare-release.outputs.version }}/
        Status: ${{ needs.publish.result == 'success' ? 'Success ✅' : 'Failed ❌' }}
      success: ${{ needs.publish.result == 'success' }}
