name: "Security: Dependencies"

on:
  push:
    paths:
      - composer.lock
      - .github/workflows/security-dependencies.yml
  pull_request:
    paths:
      - composer.lock
  schedule:
    - cron: "0 9 * * 3" # Run weekly on Wednesdays at 9 AM UTC

permissions:
  contents: read

jobs:
  audit:
    name: "Vulnerability Scan"
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@2282b6a082fc605c8320908a4cca3a5d1ca6c6fe # v2.3.3
        with:
          php-version: "8.3"
          tools: composer:v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run security audit
        run: composer audit
