name: "Security: Dependencies"

on:
  push:
    paths:
      - composer.lock
      - .github/workflows/security-dependencies.yml
  pull_request:
    paths:
      - composer.lock
  schedule:
    - cron: "0 9 * * 3" # Run weekly on Wednesdays at 9 AM UTC

jobs:
  audit:
    name: "Vulnerability Scan"
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP
        uses: shivammathur/setup-php@cf4cade2721270509d5b1c766ab3549210a39a2a # v2.3.3
        with:
          php-version: "8.3"
          tools: composer:v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run security audit
        run: composer audit
