name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
        driver-opts: |
          network=host
    
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    
    - name: Run integration tests with automatic cleanup
      run: |
        # Run integration tests and capture exit code, then cleanup
        docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from test-runner
        EXIT_CODE=$?
        docker compose -f docker-compose.test.yml down -v
        exit $EXIT_CODE
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      if: always()
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: integration
        files: ./coverage/integration-cobertura.xml
        fail_ci_if_error: false

    - name: Upload test results to Codecov
      uses: codecov/test-results-action@v1
      if: always()
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: integration
        files: ./integration-junit.xml

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: integration-test-results
        path: |
          coverage/integration-cobertura.xml
          integration-junit.xml
        retention-days: 7
        if-no-files-found: warn