name: "Integration Tests"

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  integration-tests:
    name: "PHP 8.3 with Coverage"
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        run: |
          echo "Building test image with latest code..."
          docker buildx build \
            --tag evansims/openfga-laravel-integration-tests:latest \
            --file Dockerfile.integration \
            --load \
            .

          # Show image info
          echo "Built test image:"
          docker images evansims/openfga-laravel-integration-tests:latest --format "Repository: {{.Repository}} Size: {{.Size}}"

      - name: Run integration tests
        run: |
          # Use the regular compose file with the freshly built image
          docker compose -f docker-compose.integration.yml up -d openfga otel-collector
          sleep 10
          docker compose -f docker-compose.integration.yml run --rm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@4650159d642e33fdc30954ca22638caf0df6cac8 # v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: integration
          files: ./coverage/cobertura.xml
          fail_ci_if_error: true

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: integration
          file: ./junit.xml

      - name: Cleanup
        if: always()
        run: |
          docker compose -f docker-compose.integration.yml down -v
          docker ps -a --filter label=com.openfga.test=integration -q | xargs -r docker rm -f || true
